### ISSUE TITLE
how to fix this? Please help!!

### ISSUE THREAD

**Issue by aiypwzqp** [rsg98/homebridge-gpio-wpi2#13]
[3/7/2017, 2:49:01 AM] Loaded plugin: homebridge-gpio-wpi2
[3/7/2017, 2:49:01 AM] Registering platform 'homebridge-gpio-wpi2.WiringPiPlatform'
[3/7/2017, 2:49:01 AM] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:202
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:202:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)

**Comment by aiypwzqp** [comment]
I fixed this by changing the config.json file as bridge section is missing like
ORIGINAL
{ 
    "platforms": [{
          "platform" : "WiringPiPlatform",
          "name" : "Pi GPIO (WiringPi)",
          "overrideCache" : "true",
          "autoExport" : "true",
          "gpiopins" : [{
                "name" : "GPIO2",
                "pin"  : 27,
                "enabled" : "true",
                "mode" : "out",
                "pull" : "down",
                "inverted" : "false",
                "duration" : 0,
                "polling" : "true"
            },{
                "name" : "GPIO3",
                "pin"  : 22,
                "enabled" : "true",
                "mode" : "out",
                "pull" : "down",
                "inverted" : "false",
                "duration" : 0
          }]
    }]
}
that i changes is 
{

    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
 
    "platforms": [{
          "platform" : "WiringPiPlatform",
          "name" : "Pi GPIO (WiringPi)",
          "overrideCache" : "true",
          "autoExport" : "true",
          "gpiopins" : [{
                "name" : "GPIO2",
                "pin"  : 27,
                "enabled" : "true",
                "mode" : "out",
                "pull" : "down",
                "inverted" : "false",
                "duration" : 0,
                "polling" : "true"
            },{
                "name" : "GPIO3",
                "pin"  : 22,
                "enabled" : "true",
                "mode" : "out",
                "pull" : "down",
                "inverted" : "false",
                "duration" : 0
          }]
    }]
}
