### ISSUE TITLE
Missing plugin folder on Homebridge startup?

### ISSUE THREAD

**Issue by ThAtSIt416** [rsg98/homebridge-gpio-wpi2#39]
Hi there, I seem to be having trouble using this plugin with Homebridge. I start Homebridge and I get this error message: 

> [2017-12-12 01:24:27] ====================
[2017-12-12 01:24:27] ERROR LOADING PLUGIN homebridge-gpio-wpi2:
[2017-12-12 01:24:27] Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/Debug/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/Release/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/out/Debug/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/Debug/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/out/Release/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/Release/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/default/nodeWiringPi.node
 → /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/compiled/8.9.2/linux/arm/nodeWiringPi.node
    at bindings (/usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/index.js:1:99)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-gpio-wpi2/index.js:1:75)
[2017-12-12 01:24:27] ====================

It seems that there are missing folders in /usr/local/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi which I can confirm because I cannot find 'build' using 'cd' which is suppose to be located in that spot?

I believe I have installed the plugin correctly using:

> npm install -g homebridge-gpio-wpi2

and I also installed wiring pi as well. 

Any ideas?

**Comment by ThAtSIt416** [comment]
For anyone that faces this same issue, I resolved it by uninstalling homebridge-gpio-wpi2 using 
`cd /usr/lib/node_modules`
`sudo rm -rf homebridge-gpio-wpi2`

and then using `sudo npm install -g homebridge-gpio-wpi2 --unsafe-perm` to reinstall.

I believe this may have something to do with the way I installed Homebridge at the start using 
`sudo npm install -g --unsafe-perm homebridge`

-T
