### ISSUE TITLE
ERROR LOADING PLUGIN homebridge-gpio-wpi2

### ISSUE THREAD

**Issue by dcaccount** [rsg98/homebridge-gpio-wpi2#46]
Hello,
I have successfully installed Homebridge and I have installed homebridge-gpio-wpi2 as per instructions found:

`sudo apt-get install wiringpi`
`sudo npm install -g homebridge-gpio-wpi2`

But when I launch Homebridge I always get following error:

> ERROR LOADING PLUGIN homebridge-gpio-wpi2:
[2018-4-25 14:56:19] Error: Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/nodeWiringPi.node
 → /usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/Debug/nodeWiringPi.node
 → /usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/Release/nodeWiringPi.node
 → /usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/out/Debug/nodeWiringPi.node
 → /usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/Debug/nodeWiringPi.node
 → /usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/out/Release/nodeWiringPi.node
 → /usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/Release/nodeWiringPi.node
 → /usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/build/default/nodeWiringPi.node
 → /usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/compiled/8.11.1/linux/arm/nodeWiringPi.node
    at bindings (/usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/index.js:1:99)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-gpio-wpi2/index.js:1:75)

I tried to read all similar problems but I have not been able to save it.

Can anyone please help?
Thanks,
Dan

**Comment by rsg98** [comment]
Can you try:

npm install node-wiring-pi

And post the messages / errors it generates?

**Comment by dcaccount** [comment]
Thanks,
In few minutes I will post it, as I am restoring the system for a fresh install.

By the way, instead of:
sudo npm install -g homebridge-gpio-wpi2

shall I try?

sudo npm install -g —unsafe-perm homebridge-gpio-wpi2?

Thanks,
dan


Il giorno 25 apr 2018, alle ore 15:28, Richard Grime <notifications@github.com> ha scritto:

Can you try:

npm install node-wiring-pi

And post the messages / errors it generates?

**Comment by dcaccount** [comment]
Hello,
it looks like I have solved the issue.
I have installed with:
`sudo npm install -g --unsafe-perm  homebridge-gpio-wpi2`

Any idea why?

Thanks,
dan
