### ISSUE TITLE
Error loading plugin homebridge-gpio-wpi2

### ISSUE THREAD

**Issue by edbpereira** [rsg98/homebridge-gpio-wpi2#48]
hey gyus, i need some help here.
When i run homebridge get the following error:

[2018-5-2 20:02:54] ==================== [2018-5-2 20:02:54] ERROR LOADING PLUGIN homebridge-gpio-wpi2: [2018-5-2 20:02:54] Error: Could not locate the bindings file. Tried: → /opt/node/lib/nodemodules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/b uild/nodeWiringPi.node → /opt/node/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/b uild/Debug/nodeWiringPi.node → /opt/node/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/b uild/Release/nodeWiringPi.node → /opt/node/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/o ut/Debug/nodeWiringPi.node → /opt/node/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/D ebug/nodeWiringPi.node → /opt/node/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/o ut/Release/nodeWiringPi.node → /opt/node/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/R elease/nodeWiringPi.node → /opt/node/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/b uild/default/nodeWiringPi.node → /opt/node/lib/node_modules/homebridge-gpio-wpi2/node_modules/node-wiring-pi/c ompiled/8.11.1/linux/arm/nodeWiringPi.node at bindings (/opt/node/lib/node_modules/homebridge-gpio-wpi2/node_modules/bi ndings/bindings.js:88:9) at Object.<anonymous> (/opt/node/lib/node_modules/homebridge-gpio-wpi2/node modules/node-wiring-pi/index.js:1:99) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object.<anonymous> (/opt/node/lib/node_modules/homebridge-gpio-wpi2/index .js:1:75) [2018-5-2 20:02:54] ==================== [2018-5-2 20:02:54] No plugins found. See the README for information on installi ng plugins. [2018-5-2 20:02:54] config.json (/home/pi/.homebridge/config.json) not found. Setup Payload: X-HM://0023ISYWYLN8P

The nodejs version is 9.0.0 and i installed wiringpi and homebridge-gpio-wpi2 without problems.

Any idea?

**Comment by DavideVito** [comment]
I have the same problem
