### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by wingdu** [rsg98/homebridge-gpio-wpi2#59]
Apr 28 16:27:05 raspberrypi homebridge[11300]: [4/28/2019, 4:27:05 PM] Loading 1 accessories...
Apr 28 16:27:05 raspberrypi homebridge[11300]: [4/28/2019, 4:27:05 PM] [Test] Initializing mi-flower-care accessory...
Apr 28 16:27:05 raspberrypi homebridge[11300]: [4/28/2019, 4:27:05 PM] [Pi GPIO (WiringPi)] GPIO2 Configure GPIO Pin 9aec2d2c-b026-4884-8b57-8b45093a8559
Apr 28 16:27:05 raspberrypi homebridge[11300]: [4/28/2019, 4:27:05 PM] TypeError: Cannot read property 'name' of undefined
Apr 28 16:27:05 raspberrypi homebridge[11300]:     at platform.gpiopins.find.p (/usr/local/lib/node_modules/homebridge-gpio-wpi2/index.js:67:80)
Apr 28 16:27:05 raspberrypi homebridge[11300]:     at Array.find (<anonymous>)
Apr 28 16:27:05 raspberrypi homebridge[11300]:     at WPiPlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-gpio-wpi2/index.js:67:40)
Apr 28 16:27:05 raspberrypi homebridge[11300]:     at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:386:24)
Apr 28 16:27:05 raspberrypi homebridge[11300]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:8)
Apr 28 16:27:05 raspberrypi homebridge[11300]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Apr 28 16:27:05 raspberrypi homebridge[11300]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 28 16:27:05 raspberrypi homebridge[11300]:     at Module._compile (internal/modules/cjs/loader.js:701:30)
Apr 28 16:27:05 raspberrypi homebridge[11300]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
Apr 28 16:27:05 raspberrypi homebridge[11300]:     at Module.load (internal/modules/cjs/loader.js:600:32)
Apr 28 16:27:05 raspberrypi homebridge[11300]: [4/28/2019, 4:27:05 PM] Got SIGTERM, shutting down Homebridge...
Apr 28 16:27:06 raspberrypi homebridge[11300]: [4/28/2019, 4:27:06 PM] [VorwerkVacuumRobot] getRobots | Found robot #1 named "Eve" with serial "59VE8X1X-2C6B7DBF4B57"

**Comment by mkd337** [comment]
Hey, try following

cd .homebridge/accessories

you should see there cachedAccessries which you need to remove by following

sudo rm cachedAccessories

then run homebridge again
