### ISSUE TITLE
TypeError: "list" argument must be an Array of Buffers

### ISSUE THREAD

**Issue by Rafaelbf84** [rsg98/homebridge-gpio-wpi2#60]
[11/7/2019, 11:15:14 PM] [Pi GPIO (WiringPi)] Loading cached GPIO pins complete
[11/7/2019, 11:15:14 PM] Homebridge is running on port 51826.
[11/7/2019, 11:16:01 PM] TypeError: "list" argument must be an Array of Buffers
    at Function.Buffer.concat (buffer.js:314:13)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:26:35)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at Object.encode (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/tlv.js:51:39)
    at HAPServer._handlePairStepFive (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:459:21)
    at HAPServer._handlePairStepFour (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:439:8)
    at HAPServer._handlePairStepThree (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:413:8)
    at HAPServer._handlePair (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:315:10)
    at HAPServer.<anonymous> (/opt/node/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
[11/7/2019, 11:16:01 PM] Got SIGTERM, shutting down Homebridge...

**Comment by Rafaelbf84** [comment]
When I try to add a new accessory.

**Comment by Error-freeIT** [comment]
I ran into the same issue while setting up Homebrdige on a Raspberry Pi 2 (ARMv6 processor). I needed to update from Node.js v6.17.0 to v8.11.3 by following [these steps](https://warlord0blog.wordpress.com/2018/06/27/node-js-v8-on-raspberry-pi-zero/).

```wget https://nodejs.org/dist/v8.11.3/node-v8.11.3-linux-armv6l.tar.xz
tar -xvf node-v8.11.3-linux-armv6l.tar.xz
cd node-v8.11.3-linux-armv6l
sudo cp -R * /usr/local/``
