### ISSUE TITLE
Can't get homebridge to start with homebridge-gpio-wpi2

### ISSUE THREAD

**Issue by GatoPharaoh** [rsg98/homebridge-gpio-wpi2#8]
Whenever I try to start my homebridge with homebridge-gpio-wpi2 activated, I get this error

====================
[2017-02-08 22:53:49] ERROR LOADING PLUGIN homebridge-gpio-wpi2:
[2017-02-08 22:53:49] Error: Cannot find module './build/Release/node_sleep.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-gpio-wpi2/node_modules/sleep/index.js:1:75)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
[2017-02-08 22:53:49] ====================

Any ideas?
Thanks in advance

**Comment by rsg98** [comment]
Looks like the "sleep" module failed to install properly. If you run

npm install sleep

Does it generate any errors?

**Comment by rsg98** [comment]
Assuming this is resolved - re-open if not.
