### ISSUE TITLE
Failure to start

### ISSUE THREAD

**Issue by maikischa** [rsg98/homebridge-gpio-wpi2#9]
When i try to start the module I get this error message

[2017-02-19 16:40:54] Loaded plugin: homebridge-gpio-wpi2
[2017-02-19 16:40:54] Registering platform 'homebridge-gpio-wpi2.WiringPiPlatform'
[2017-02-19 16:40:54] ---
/usr/lib/node_modules/homebridge/lib/server.js:202
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:202:31)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)

**Comment by maikischa** [comment]
Sorry. My fault. Fault config file
